EXAMPLES/DJANGO/djsimpform/djsimpform/urls.py
"""djsimpform URL Mapping

The `urlpatterns` list maps URLs to views. More information:
    https://docs.djangoproject.com/en/2.1/topics/http/urls/

Function views:
    1. Add an import:  from my_app import views
    2. Add entry to urlpatterns:  path('view_name', views.view_name, name='view_name')

Class-based views:
    1. Add an import:  from my_app.views import Home
    2. Add entry to urlpatterns:  path('view_name', ViewName.as_view(), name='view_name')

Including another (usually an app's) URLconf:
    1. Import the include() function: from django.urls import url, include
    2. Add a URL to urlpatterns:  path('appname', include('app.urls', namespace="app"))
    Path may be blank; in that case only the app URL is used

    -----------------------------------------------------------------------------------
    NOTE: when using the namespace argument with include(), the app's urls.py MUST have

        app_name="APPNAME"

    before  urlpatterns = ...
    -----------------------------------------------------------------------------------
"""
from django.conf import settings
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin', admin.site.urls),
    path('', include('simpform.urls', namespace="simpform")),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__', include(debug_toolbar.urls)),
    ] + urlpatterns

EXAMPLES/DJANGO/djsimpform/simpform/urls.py
"""
URL Configuration for simpform
"""
from django.urls import path
from . import views   # import views from app

app_name = 'simpform'

urlpatterns = [
    # add url patterns for the simpform app here

    # Example:
    path('', views.home, name='home'),
]

EXAMPLES/DJANGO/djsimpform/simpform/forms.py
from django import forms

# Create your forms here.

class SimpleForm(forms.Form):
    user_name = forms.CharField(max_length=32)

EXAMPLES/DJANGO/djsimpform/simpform/views.py
from django.shortcuts import render
from .forms import SimpleForm

def home(request):
    if request.method == "POST":
        simpleform = SimpleForm(request.POST)
        if simpleform.is_valid():
            user_name = simpleform.cleaned_data["user_name"]
    else:
        user_name = ''
        simpleform = SimpleForm()

    context = {
        'message': "Welcome to Simple Form Demo App",
        'simpleform': simpleform,
        'username': user_name,
    }
    return render(request, 'simpform/home.html', context)

EXAMPLES/DJANGO/djsimpform/simpform/templates/simpform/home.html
{% extends "simpform/simpform_base.html" %}
{% block content %}
<div class="container">
<form action="{% url 'simpform:home' %}" method="post">
    {% csrf_token %}
    {{ simpleform.as_p }}
    <input type="submit" value="Submit"/>
    <hr/>
    {% if username %}
    Welcome, {{ username }}
    {% endif %}
</form>
</div>
{% endblock content %}

EXAMPLES/DJANGO/djsimpform/simpform/templates/simpform/sample.html
{% extends "simpform/simpform_base.html" %}
{% block content %}
<div class="container">
<form action =
</div>
{% endblock content %}

EXAMPLES/DJANGO/djsimpform/simpform/templates/simpform/simpform_base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}Simple Form Demo App{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    {% block css %}
    <!-- Latest compiled and minified Bootstrap 4 beta CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">

    <!-- Your stuff: Third-party CSS libraries go here -->

    {% endblock css %}

  </head>

  <body>

    <div class="container">

      {% block header %}{% endblock header %}
      {% block content %}
        <p>Default content for Simple Form Demo App</p>
      {% endblock content %}
      {% block footer %}{% endblock footer %}

    </div> <!-- /container -->

    <!-- Javascript Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      <!-- Required by Bootstrap v4 beta -->
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

      <!-- Third-party javascript libraries go here -->

      <!-- App-specific Javascript in this file -->

      <script src="{% static 'js/simpform.js' %}"></script>


    {% endblock javascript %}

  </body>
</html>