EXAMPLES/DJANGO/djsuper/djsuper/urls.py
"""djsuper URL Mapping

The `urlpatterns` list maps URLs to views. More information:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/

Function views:
    1. Add an import:  from my_app import views
    2. Add entry to urlpatterns:  url(r'^$', views.home, name='home')

Class-based views:
    1. Add an import:  from my_app.views import Home
    2. Add entry to urlpatterns:  url(r'^$', Home.as_view(), name='home')

Including another (usually an app's) URLconf:
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls', namespace="blog"))
"""
from django.conf import settings
from django.contrib import admin

# site-wide route mapping
from django.urls import path, include
urlpatterns = [
    path('admin', admin.site.urls),
    path('', include('superheroes.urls')),
]

EXAMPLES/DJANGO/djsuper/superheroes/urls.py
"""
URL Configuration for superheroes
"""
from django.urls import path
from . import views   # import views from app
from . import views404
from . import viewsbasictemplate
from . import viewstemplate
from . import viewsqueries

app_name = 'superheroes'


urlpatterns = [
    path('', views.home, name='home'),
    path('hero/<str:hero_name>/', views.hero, name="hero"),
    path('hero404x/<str:hero_name>/', views404.hero404, name="hero404"),
    path('hero404sc/<str:hero_name>/', views404.hero404sc, name="hero404sc"),
    path(
        'herotemplate101/<str:hero_name>/',
        viewsbasictemplate.hero_basic_template,
        name="herobasictemplate",
    ),
    path(
        'herohardway/<str:hero_name>/',
        viewstemplate.hero_hard_way,
        name="herohardway",
    ),
    path(
        'heroeasyway/<str:hero_name>/',
        viewstemplate.hero_easy_way,
        name="heroeasyway",
    ),
    path(
        'herolookups/<str:hero_name>/',
        viewstemplate.hero_lookups,
        name="herolookups",
    ),
    path(
        'herofilters/<str:hero_name>/',
        viewstemplate.hero_filters,
        name="herofilters",
    ),
    path(
        'herotags/<str:hero_name>/',
        viewstemplate.hero_tags,
        name="herotags",
    ),
    path(
        'herodetails/<str:hero_name>/',
        viewstemplate.hero_details,
        name="herodetails",
    ),
    path(
        'heroescape/<str:hero_name>/',
        viewstemplate.hero_escape,
        name="heroescape",
    ),
    path(
        'herourls/',
        viewstemplate.hero_urls,
        name="herourls",
    ),
    path(
        'herostatic/<str:hero_name>/',
        viewstemplate.hero_static,
        name="herostatic",
    ),
    path(
        'heroqueries/',
        viewsqueries.hero_queries,
        name="heroqueries",
    ),
]

EXAMPLES/DJANGO/djsuper/superheroes/models.py
from django.db import models

class Power(models.Model):
    name = models.CharField(max_length=32, unique=True)
    description = models.CharField(max_length=512)

    def __str__(self):
        return self.name

class City(models.Model):
    name = models.CharField(max_length=32, unique=True)

    def __str__(self):
        return self.name

class Enemy(models.Model):
    name = models.CharField(max_length=32, unique=True)
    powers = models.ManyToManyField(Power)

    def __str__(self):
        return self.name

class Superhero(models.Model):
    name = models.CharField(max_length=32, unique=True)
    real_name = models.CharField(max_length=32)
    secret_identity = models.CharField(max_length=32)
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    powers = models.ManyToManyField(Power)
    enemies = models.ManyToManyField(Enemy)

    def __str__(self):
        return self.name

EXAMPLES/DJANGO/djsuper/superheroes/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from .models import Superhero

def home(request):
    return HttpResponse("Welcome to the superhero app")

def hero(request, hero_name):
    request.session['name'] = hero_name
    s = Superhero.objects.get(name=hero_name)
    return HttpResponse(
        "{} is really {}".format(s.secret_identity, s.name)
    )

def hero_by_id(request, pk):
    hero_name = request.session.get('name', '')
#    s = Superhero.objects.get(id=pk)
    s = get_object_or_404(Superhero, id=pk)  # automagically uses 404xx.html template
    return HttpResponse(
        "{} ({})".format(s.name, s.secret_identity)
    )

EXAMPLES/DJANGO/djsuper/superheroes/templates/hero_details.html
{% extends "superheroes_base.html" %}

{% block content %}

<h1>{{ hero.name }}</h1>
<h2>Secret Identity: {{ hero.secret_identity }}</h2>
<h2>Real Name: {{ hero.real_name }}</h2>
<h3>Powers: {{ hero.powers.all | join:", "}}</h3>
<h3>Enemies: {{ hero.enemies.all | join:", " }}</h3>

<a href="{% url 'superheroes:herourls' %}">Return to hero list</a>
{% endblock %}

EXAMPLES/DJANGO/djsuper/superheroes/templates/hero_filters.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ hero.name }}</title>
</head>
<body>
<h1>{{ hero.name }}</h1>
<h2>Secret Identity: {{ hero.secret_identity | upper }}</h2>
<h2>Secret Identity (short):
    {{ hero.secret_identity | slice:"0:5" }}
</h2>
<h2>Real Name: {{ hero.real_name | upper }}</h2>
<h2>First enemy: {{ hero.enemies.all.0 }}</h2>
<h3>Raw enemies list: {{ hero.enemies.all }}</h3>
<h3>Number of enemies: {{ hero.enemies.all | length }}</h3>
<h3>Enemies: {{ hero.enemies.all | join:", " }}</h3>
<h3>Enemies: <br/>{{ hero.enemies.all | join:"<br/>" }}</h3>

</body>
</html>

EXAMPLES/DJANGO/djsuper/superheroes/templates/hero_urls.html
{% extends "superheroes_base.html" %}

{% block title %}{{ title }}{% endblock title %}

{% block content %}

<h1>Pick a hero (URL version):</h1>

{% for hero in superheroes %}
<h3>
    <a href="{% url 'superheroes:herodetails' hero.name  %}">{{ hero.name }}</a>
</h3>
{% endfor %}

{% endblock %}

</body>
</html>