dogs/dogs/urls.py
"""dogs URL Mapping

The `urlpatterns` list maps URLs to views. More information:
    https://docs.djangoproject.com/en/2.1/topics/http/urls/

Function views:
    1. Add an import:  from my_app import views
    2. Add entry to urlpatterns:  path('view_name', views.view_name, name='view_name')

Class-based views:
    1. Add an import:  from my_app.views import Home
    2. Add entry to urlpatterns:  path('view_name', ViewName.as_view(), name='view_name')

Including another (usually an app's) URLconf:
    1. Import the include() function: from django.urls import url, include
    2. Add a URL to urlpatterns:  path('appname', include('app.urls', namespace="appname"))
    Path may be blank; in that case only the app URL is used

    -----------------------------------------------------------------------------------
    NOTE: when using the namespace argument with include(), the app's urls.py MUST have

        app_name="APPNAME"

    before  urlpatterns = ...
    -----------------------------------------------------------------------------------
"""
from django.conf import settings
from django.urls import path, include
from django.contrib import admin

# site-wide route mapping
urlpatterns = [
    path('admin/', admin.site.urls),
    # To include urls from an app:
    #
    # path('', include('app.urls', namespace="appname")),  # delegate to app's URL config
    #
    # note: if path (1st arg) is not empty, it will be a prefix to app URL
    # and will follow the hostname, before the path in the app's urls.py
    #
    # i.e., if path here is "spam" and path in app/urls.py is "home",
    # url will be HOSTNAME:PORT/spam/home
    #
    # if first arg is empty, then paths in app.urls will immediately follow
    #  the host name

    # To configure a single view:
    #
    # from app.views import myview
    # path('viewpath', myview, name="myview")
    path('', include('dogs_core.urls', namespace='dogs_core')),
]

# include Django Debug toolbar if DEBUG is set
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__', include(debug_toolbar.urls)),
    ] + urlpatterns

dogs/dogs_core/urls.py
"""
URL Configuration for dogs_core
"""
from django.urls import path
from . import views   # import views from app

app_name = "dogs_core"

urlpatterns = [
    # add url patterns for the dogs_core app here

    # Examples:
    # path('', views.home, name='home'),
    # path('thing', views.thing, name='thing'),
    path('', views.home, name='home'),
    path('details/<int:pkid>', views.dog_details, name='dog_details'),
    path('dogadd', views.dog_add, name='dog_add'),
    path('other', views.other_form, name='other'),
    path('dog_list', views.DogListView.as_view(), name="dog_list"),
    path('dog_list_by_name', views.DogListByNameView.as_view(), name="dog_list_by_name"),
    path('dog_detail/<int:pk>', views.DogDetailView.as_view(), name="dog_detail"),
    path('dog_detail_by_name/<str:name>', views.DogDetailByNameView.as_view(), name="dog_detail_by_name"),
]

dogs/dogs_core/models.py
from django.db import models

# Create your models here.
class Breed(models.Model):
    name = models.CharField(max_length=32, unique=True)

    def __str__(self):
        return self.name

class Dog(models.Model):
    name = models.CharField(max_length=32)
    breed = models.ForeignKey(Breed, on_delete = models.CASCADE)

    MALE = 'M'
    FEMALE = 'F'
    SEX_CHOICES = [
        (MALE, 'Male'),
        (FEMALE, 'Female'),
    ]
    sex = models.CharField(max_length=1, choices=SEX_CHOICES)
    is_neutered = models.BooleanField(default=False)
    is_biter = models.BooleanField(default=False)
    favorite_toy = models.CharField(max_length=32, null=True)

    def __str__(self):
        return '{} ({})'.format(self.name, self.breed)

dogs/dogs_core/forms.py
from django import forms
from .models import Dog, Breed

class DogAddForm(forms.ModelForm):
    class Meta:
        model = Dog
        exclude = []
        # or
        # fields = ['name', 'breed']

class OtherForm(forms.Form):
    dog_name = forms.CharField(label='Name', widget=forms.TextInput(attrs={"class": "name"}), required=False)
    dog_breed = forms.ModelChoiceField(
        queryset=Breed.objects.all(),
        label='Breed',
        widget=forms.TextInput(attrs={"class": "breed"}),
        required=False
    )
    dog_sex = forms.ChoiceField(label='Sex', choices=Dog.SEX_CHOICES, required=False)
    dog_is_neutered = forms.BooleanField(label='Is neutered?', required=False)

dogs/dogs_core/views.py
from django.http import HttpResponse # only used in class (see comment below)
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.urls import reverse
from .models import Dog, Breed
from .forms import DogAddForm, OtherForm
from django.db.models import Q
import pdb

# Create your views here.
def home(request):
    dogs = Dog.objects.all()
    context = {
        'page_title': 'Welcome to the Dogs',
        'dogs': dogs,
        'home': True,
    }
    return render(request, 'dogs_core/home.html', context)

def dog_details(request, pkid):
    dog = get_object_or_404(Dog, pk=pkid)
    return render(request, 'dogs_core/dog_details.html', {'dog': dog})

def dog_add(request):
    if request.method == 'POST':
        form = DogAddForm(request.POST)  # fill in form with user data
        if form.is_valid():
            dog = Dog()
            dog.name = form.cleaned_data.get('name')
            breed_id = form.data.get('breed')
            dog.breed = Breed.objects.get(pk=breed_id)
            dog.sex = form.cleaned_data.get('sex')
            dog.is_neutered = form.cleaned_data.get('is_neutered')
            dog.save()  # add to DB

            context = {
                'page_title': f"Added {dog.name}",
                'dog': dog,
                'added': True,
            }
            return render(request, 'dogs_core/dog_details.html', context)
    else:
        form = DogAddForm()
        context = {
            'page title': 'Add a Dog',
            'form': form,
        }
        return render(request, 'dogs_core/dog_add.html', context)

def other_form(request):
    if request.method == 'POST':  # filled out form
        form = OtherForm(request.POST)  # fill in form from incoming data
        if form.is_valid():
            dog_name = form.cleaned_data.get('dog_name')
            query = Q()
            if dog_name:
                query &= Q(dog_name=dog_name)
            dog_sex = form.cleaned_data.get('dog_sex')
            if dog_sex:
                query &= Q(dog_sex=dog_sex)
            results = Dog.objects.filter(query)

    else:  # empty form
        form = OtherForm()
        context = {
        'page title': 'Other Form',
        'form': form,
        }
        return render(request, 'dogs_core/other_form.html', context)

# example without template (only used in class -- always use templates in real life):
# def home(request):
#     return HttpResponse("Welcome to dogs_core")

# example with template (normal Django approach)
# def home(request):
#     context = { 'message': "Welcome to dogs_core" }
#     return render(request, 'dogs_core/home.html', context)
class DogListView(ListView):
    model = Dog   # template will be dog_list.html by default
    # template_name = "dogs_core/whatever.html"

class DogListByNameView(ListView):
    model = Dog   # template will be dog_list.html by default
    template_name = "dogs_core/dog_list_by_name.html"

class DogDetailView(DetailView):
    model = Dog  # template will be dog_detail.html

class DogDetailByNameView(DetailView):
    model = Dog  # template will be dog_detail.html

    def get_object(self, queryset=None):
        return Dog.objects.get(name=self.kwargs.get("name"))

class BreedListView(ListView):
    model = Breed

class BreedDetailView(DetailView):
    model = Breed

dogs/dogs_core/templates/dogs_core/breed_detail.html
{% extends "dogs_core/dogs_core_base.html" %}
{% block content %}
<div class="container">
Sample content for dogs_core
</div>
{% endblock content %}

dogs/dogs_core/templates/dogs_core/breed_form.html
{% extends "dogs_core/dogs_core_base.html" %}
{% block content %}

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

{% endblock %}

dogs/dogs_core/templates/dogs_core/breed_list.html
{% extends "dogs_core/dogs_core_base.html" %}
{% block content %}
<div class="container">
Sample content for dogs_core
</div>
{% endblock content %}

dogs/dogs_core/templates/dogs_core/dog_add.html
{% extends "dogs_core/dogs_core_base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
<h1>{{ page_title }}</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form | crispy }}
        <input type="submit" value="Add"/>
    </form>
</div>
{% endblock content %}

dogs/dogs_core/templates/dogs_core/dog_detail.html
{% extends "dogs_core/dogs_core_base.html" %}
{% block content %}

<h1>{{ object.name }}</h1>
<h2>Breed: {{ object.breed }}</h2>
<h2>Sex: {{ object.sex }}</h2>
<h3>Is neutered: {{ object.is_neutered }}</h3>

<a href="{% url 'dogs_core:dog_list' %}">Return to list</a>

{% endblock %}

dogs/dogs_core/templates/dogs_core/dog_details.html
{% extends "dogs_core/dogs_core_base.html" %}
{% block content %}
<div class="container">
<h1>{{ dog.name }}
{% if added %}
    <span class="note">ADDED</span>
{% endif %}

</h1>
    <h2>{{ dog.breed }}</h2>
    <h2>{{ dog.sex }}</h2>
    <h2>{{ dog.is_neutered }}</h2>
</div>
{% endblock content %}

dogs/dogs_core/templates/dogs_core/dog_form.html
{% extends "dogs_core/dogs_core_base.html" %}

{% block content %}

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

{% endblock %}

dogs/dogs_core/templates/dogs_core/dog_list.html
{% extends "dogs_core/dogs_core_base.html" %}

{% block content %}

<h1>Pick a dog:</h1>
<h2>(minimal class-based list view)</h2>

{% for dog in object_list %}
<h3><a
  href="{% url 'dogs_core:dog_detail' dog.id %}">
    {{ dog.name }}
</a>
    {{ dog.breed }}
</h3>
{% endfor %}

{% endblock %}

dogs/dogs_core/templates/dogs_core/dog_list_by_name.html
{% extends "dogs_core/dogs_core_base.html" %}

{% block content %}

<h1>Pick a dog:</h1>
<h2>(minimal class-based list view)</h2>

{% for dog in object_list %}
<h3><a
  href="{% url 'dogs_core:dog_detail_by_name' dog.name %}">
    {{ dog.name }}
</a>
    {{ dog.breed }}
</h3>
{% endfor %}

{% endblock %}

dogs/dogs_core/templates/dogs_core/dogs_core_base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}dogs_core{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    {% block css %}
    <!-- Latest compiled and minified Bootstrap 4 beta CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">

    <!-- Your stuff: Third-party CSS libraries go here -->

    {% endblock css %}

  </head>

  <body>

    <div class="container">

      {% block header %}{% endblock header %}
      {% block content %}
        <p>Default content for dogs_core</p>
      {% endblock content %}
      {% block footer %}
      {% if not home %}
      <h3><a href="{% url 'dogs_core:home' %}">Return to home page</a></h3>
      {% endif %}
      {% endblock footer %}

    </div> <!-- /container -->

    <!-- Javascript Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      <!-- Required by Bootstrap v4 beta -->
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

      <!-- Third-party javascript libraries go here -->

      <!-- App-specific Javascript in this file -->

      <script src="{% static 'js/dogs_core.js' %}"></script>


    {% endblock javascript %}

  </body>
</html>

dogs/dogs_core/templates/dogs_core/home.html
{% extends "dogs_core/dogs_core_base.html" %}
{% block content %}
<div class="container">
<h1>Welcome to the Dogs</h1>
    {% for dog in dogs %}
    <h2><a href="{% url 'dogs_core:dog_details' dog.id %}">{{ dog.name }}</a></h2>
    {% endfor %}
    <hr/>
    <a href="{% url 'dogs_core:dog_add' %}">Add another dog</a>
</div>
{% endblock content %}

dogs/dogs_core/templates/dogs_core/other_form.html
{% extends "dogs_core/dogs_core_base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <h1>{{ page_title }}</h1>
    <form action="{% url 'dogs_core:other' %}" method="post">
        {% csrf_token %}
        {{ form | crispy }}
        <input type="submit" value="Add"/>
    </form>
</div>
{% endblock content %}

dogs/dogs_core/templates/dogs_core/sample.html
{% extends "dogs_core/dogs_core_base.html" %}
{% block content %}
<div class="container">
Sample content for dogs_core
</div>
{% endblock content %}